### ISSUE TITLE
For help!! Some questions 

### ISSUE THREAD

**Issue by xcxzzx-1** [habernal/dkpro-core-rst#1]
Hello, I have downloaded the project "dkpro-core-rst", but the IDA eclipse shows that it misses the following classes. Can you give me some advices or send me a project that is compiled successfully? I will be very glad that you can reply. This is my my email xcxzzx01@163.com. Please give me a help. Than you very much!

import de.tudarmstadt.ukp.dkpro.core.rst.core.type.DiscourseRelation;
import de.tudarmstadt.ukp.dkpro.core.rst.core.type.EDU;
import de.tudarmstadt.ukp.dkpro.core.rst.core.type.RSTTreeNode;

**Comment by habernal** [comment]
Hello, I guess the problem is due to Eclipse and its poor integration with Maven. Try to first compile it using maven (`mvn compile`), it should also generate these classes that are currently missing. These are dynamically generated from UIMA xml descriptors.

**Comment by xcxzzx-1** [comment]
Thank you very much! I have done what you tell me and it works successfully. You are so cool!!

**Comment by xcxzzx-1** [comment]
Thank you very much!! I have done what you say and it works successfully. You are so cool!!




At 2017-03-29 02:42:15, "Ivan Habernal" <notifications@github.com> wrote:


Hello, I guess the problem is due to Eclipse and its poor integration with Maven. Try to first compile it using maven (mvn compile), it should also generate these classes that are currently missing. These are dynamically generated from UIMA xml descriptors.
